# Better than nothing
name: Assert it builds
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checout commit
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Install deps
        run: >
          sudo apt-get install -y
          libavcodec-dev
          libavutil-dev
          libavformat-dev
          libswscale-dev
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Build
        run: go build
