# Better than nothing
name: Assert it builds
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checout commit
        uses: actions/checkout@v2
      - name: Install Go
        shell: bash
        run: |
          VERSION=`wget -q -O- https://golang.org/VERSION?m=text`
          wget -q -O- \
            "https://dl.google.com/go/${VERSION}.linux-amd64.tar.gz" \
            | sudo tar xpz -C /usr/local
          echo /usr/local/go/bin >> $GITHUB_PATH
      - name: Install deps
        run: >
          sudo apt-get install -y
          libavcodec-dev
          libavutil-dev
          libavformat-dev
          libswscale-dev
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Build
        run: go build
