# Better than nothing
name: Assert it builds
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checout commit
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Install deps
        run: >
          apt-get install -y
            libavcoded-dev
            libavutil-dev
            libavformat-dev
            libswscale-dev
      - name: Build
        run: go build
